///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class FoodListModel {
/*
{
  "id": 1,
  "name": "Chocolate Cake",
  "description": "A delicious chocolate cake.",
  "userId": 1,
  "categoryId": 1,
  "star": 5,
  "foodPhoto": "chocolate_cake.jpg",
  "ownPhoto": "null",
  "ownName": "null"
} 
*/

  int? id;
  String? name;
  String? description;
  int? userId;
  int? categoryId;
  int? star;
  String? foodPhoto;
  String? ownPhoto;
  String? ownName;

  FoodListModel({
    this.id,
    this.name,
    this.description,
    this.userId,
    this.categoryId,
    this.star,
    this.foodPhoto,
    this.ownPhoto,
    this.ownName,
  });
  FoodListModel.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    name = json['name']?.toString();
    description = json['description']?.toString();
    userId = json['userId']?.toInt();
    categoryId = json['categoryId']?.toInt();
    star = json['star']?.toInt();
    foodPhoto = json['foodPhoto']?.toString();
    ownPhoto = json['ownPhoto']?.toString();
    ownName = json['ownName']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['name'] = name;
    data['description'] = description;
    data['userId'] = userId;
    data['categoryId'] = categoryId;
    data['star'] = star;
    data['foodPhoto'] = foodPhoto;
    data['ownPhoto'] = ownPhoto;
    data['ownName'] = ownName;
    return data;
  }
}
